name: pharmascheduler
description: "Aplicativo de agendamentos para representante farmacÃªutica."

publish_to:
version: 1.0.0+1

environment:
  sdk: ^3.10.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  sqflite: ^2.3.0
  path: ^1.9.0
  intl: ^0.19.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0




flutter:
  uses-material-design: true

